name: lumberjack
version: 1.2.0
description: >-
  Provides APIs for debugging and error logging, similar to loggers in other
  languages, with normal naming

environment:
  sdk: '>=2.18.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
